services:
  web:
    image: nginx:1.25.0
    container_name: web
    depends_on:
      - frontend
      - backend
    links:
      - frontend
      - backend
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  frontend:
    image: node:20.2.0
    container_name: frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 5173:5173
    working_dir: /usr/src/app
    tty: true
  backend:
    image: golang:1.20
    container_name: backend
    working_dir: /app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080
    tty: true
  db:
    image: postgres:15.3
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - 5432:5432
    tty: true
